### ISSUE TITLE
Doesn't seem to work with hyphenated filenames

### ISSUE THREAD

**Issue by brandonpittman** [jacob-ebey/github-md#1]
## Direct to file
- https://github-md.com/brandonpittman/site/blob/main/blog/on-use-presence.md
- https://github-md.com/brandonpittman/site/blob/main/blog/foobar.md

## github-md links
- https://github-md.com/brandonpittman/site/main/blog/on-use-presence.md
- https://github-md.com/brandonpittman/site/main/blog/foobar.md

Both of these Markdown files exist on GitHub, but the filename with hyphens returns `{error: "not found"}`. The one without hyphens returns the data.

**Comment by jacob-ebey** [comment]
Check again, just clicked through them and they seem fine.

**Comment by brandonpittman** [comment]
Seems okay now but it wasn't when I created the issue though. Sorry for creating the issue.
